jwt:
  secret: secret
ldap:
  url: ldap://localhost:389
  base: dc=blocko,dc=io
  userDn: cn=admin,dc=blocko,dc=io
  password: admin

spring:
  logging:
    level:
      org.springframework.ldap.core: debug